test.AddQuestion( new Question ("com.scorm.notebooklm.module2.q1",
                                "What is the typical duration of an Audio Overview generated by NotebookLM?",
                                QUESTION_TYPE_CHOICE,
                                new Array("1-3 minutes", "5-15 minutes", "20-30 minutes", "30-60 minutes"),
                                "5-15 minutes",
                                "obj_module2")
                );

test.AddQuestion( new Question ("com.scorm.notebooklm.module2.q2",
                                "How can you customize an Audio Overview in NotebookLM?",
                                QUESTION_TYPE_CHOICE,
                                new Array("By selecting voice characteristics", "By providing focus instructions", "By adjusting playback speed", "By choosing background music"),
                                "By providing focus instructions",
                                "obj_module2")
                );

test.AddQuestion( new Question ("com.scorm.notebooklm.module2.q3",
                                "Which of the following is NOT included in Audio Overviews?",
                                QUESTION_TYPE_CHOICE,
                                new Array("Two-host conversational dialogue", "Clickable citations", "High-level synthesis of sources", "Key insights from documents"),
                                "Clickable citations",
                                "obj_module2")
                );

test.AddQuestion( new Question ("com.scorm.notebooklm.module2.q4",
                                "What type of prompt is most effective for cross-source analysis?",
                                QUESTION_TYPE_CHOICE,
                                new Array("'Summarize this document'", "'Compare X and Y across all my sources'", "'What is the main topic?'", "'Tell me everything'"),
                                "'Compare X and Y across all my sources'",
                                "obj_module2")
                );

test.AddQuestion( new Question ("com.scorm.notebooklm.module2.q5",
                                "Which prompting approach starts broad and then narrows down to specific details?",
                                QUESTION_TYPE_CHOICE,
                                new Array("The Building Block Approach", "The Refinement Approach", "The Funnel Approach", "The Synthesis Approach"),
                                "The Funnel Approach",
                                "obj_module2")
                );

test.AddQuestion( new Question ("com.scorm.notebooklm.module2.q6",
                                "What happens to your chat history when you share a notebook with collaborators?",
                                QUESTION_TYPE_CHOICE,
                                new Array("It becomes visible to all collaborators", "It remains private to you", "It is deleted for privacy", "It is merged with others' chats"),
                                "It remains private to you",
                                "obj_module2")
                );

test.AddQuestion( new Question ("com.scorm.notebooklm.module2.q7",
                                "Which permission level allows adding and removing sources but NOT sharing the notebook with others?",
                                QUESTION_TYPE_CHOICE,
                                new Array("Owner", "Editor", "Viewer", "Contributor"),
                                "Editor",
                                "obj_module2")
                );

test.AddQuestion( new Question ("com.scorm.notebooklm.module2.q8",
                                "What is a key limitation of NotebookLM collaboration features?",
                                QUESTION_TYPE_CHOICE,
                                new Array("Cannot share notebooks at all", "No real-time editing visibility", "Maximum of 2 collaborators", "All chats are public"),
                                "No real-time editing visibility",
                                "obj_module2")
                );

test.AddQuestion( new Question ("com.scorm.notebooklm.module2.q9",
                                "Which of the following is a best practice for effective prompting in NotebookLM?",
                                QUESTION_TYPE_CHOICE,
                                new Array("Ask vague questions to get broad answers", "Request structured outputs like tables or bullet points", "Avoid mentioning specific sources", "Never use follow-up prompts"),
                                "Request structured outputs like tables or bullet points",
                                "obj_module2")
                );

test.AddQuestion( new Question ("com.scorm.notebooklm.module2.q10",
                                "What can you do with a saved note in NotebookLM?",
                                QUESTION_TYPE_CHOICE,
                                new Array("Only view it within the notebook", "Export it and reference it in future queries", "Share it on social media automatically", "Convert it to an audio file"),
                                "Export it and reference it in future queries",
                                "obj_module2")
                );
