test.AddQuestion( new Question ("com.scorm.springai.interactions.concepts_1",
                                "What does the ChatClient class provide in Spring AI?", 
                                QUESTION_TYPE_CHOICE,
                                new Array("Direct database access", "A fluent API for interacting with AI models", "File system operations", "Network configuration"),
                                "A fluent API for interacting with AI models",
                                "obj_concepts")
                );
                
test.AddQuestion( new Question ("com.scorm.springai.interactions.concepts_2",
                                "A Prompt in Spring AI is the output generated by the AI model",
                                QUESTION_TYPE_TF,
                                null,
                                false,
                                "obj_concepts")
                );
                
test.AddQuestion( new Question ("com.scorm.springai.interactions.concepts_3",
                                "Which class represents the response from an AI model?", 
                                QUESTION_TYPE_CHOICE,
                                new Array("ChatRequest", "ChatResponse", "ModelOutput", "AIResult"),
                                "ChatResponse",
                                "obj_concepts")
                );
                
test.AddQuestion( new Question ("com.scorm.springai.interactions.concepts_4",
                                "Which AI providers does Spring AI support?", 
                                QUESTION_TYPE_CHOICE,
                                new Array("Only OpenAI", "Only Google Gemini", "Multiple providers including OpenAI, Google, Azure, and Anthropic", "Only local models"),
                                "Multiple providers including OpenAI, Google, Azure, and Anthropic",
                                "obj_concepts")
                );
                
test.AddQuestion( new Question ("com.scorm.springai.interactions.concepts_5",
                                "Spring AI uses dependency injection to provide ChatClient to your beans",
                                QUESTION_TYPE_TF,
                                null,
                                true,
                                "obj_concepts")
                );
                
test.AddQuestion( new Question ("com.scorm.springai.interactions.concepts_6",
                                "What is the primary purpose of a Prompt?", 
                                QUESTION_TYPE_CHOICE,
                                new Array("To store database credentials", "To provide input instructions to the AI model", "To configure the web server", "To manage user sessions"),
                                "To provide input instructions to the AI model",
                                "obj_concepts")
                );
